#====================================
#=============  common ===============
#====================================
info.app:
  name: Shipping Logistics
  description: Madcluod Shipping Service 
  version: 1.0.0-snapshot

---
#====================================
#=============== local ==============
#====================================
spring:
  profiles: local 

 ### openData DataSource
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver   
#    url: jdbc:mysql://10.100.0.143:9090/opendata
#    username: sri_dev
#    password: tkfkadlsroqkfwk)^!*
#    initial-size: 50
#    max-active: 200
#    max-idle: 100
#    min-idle: 50
#    max-wait: 10000
#    validationQuery: SELECT 1
    
#### logback set
logging:
  config: classpath:logback/logback-console.xml
  level:
    com.madcloud: DEBUG
 
#### http port set
server:
  port: 80

---
#==================================== 
#============= development ==========
#====================================
spring:
  profiles: development

### openData DataSource
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver   
#    url: jdbc:mysql://10.100.0.143:9090/opendata
#    username: sri_dev
#    password: tkfkadlsroqkfwk)^!*
#    initial-size: 50
#    max-active: 200
#    max-idle: 100
#    min-idle: 50
#    max-wait: 10000
#    validationQuery: SELECT 1
    
    
#### logback set
logging:
  config: classpath:logback/logback-service.xml
  level:
    com.madcloud: DEBUG
 
#### http port set
server:
  port: 80
   
---
#====================================
#============= production ===========
#====================================
spring:
  profiles: production

### openData DataSource
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver   
#    url: jdbc:mysql://10.100.0.143:9090/opendata
#    username: sri_dev
#    password: tkfkadlsroqkfwk)^!*
#    initial-size: 50
#    max-active: 200
#    max-idle: 100
#    min-idle: 50
#    max-wait: 10000
#    validationQuery: SELECT 1
    
#### logback set
logging:
  config: classpath:logback/logback-service.xml
  level:
    com.madcloud: INFO

  
#### http port set
server:
  port: 80
  